"""Generate Colab notebooks from cell specs. Run: python -m notebooks.build_notebooks"""
from pathlib import Path
import nbformat
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

REPO_URL = "https://github.com/arupa444/trainDronisight.git"  # set before publishing

_SETUP = [
    "# @title Setup: GPU check + repo + deps",
    "!nvidia-smi",
    f"from pathlib import Path\n"
    f"REPO='/content/repo'\n"
    f"!git clone {REPO_URL} $REPO 2>/dev/null || (cd $REPO && git pull)\n"
    "%cd $REPO\n"
    "!pip -q install uv && uv pip install --system -e .",
    "import torch; print('CUDA:', torch.cuda.is_available())",
    "from notebooks.colab_utils import mount_drive, drive_db_zip, ensure_dataset\nmount_drive()",
]

NOTEBOOKS = {
    "00_data_prep": _SETUP + [
        "# Unzip both DBs from Drive to fast local storage\n"
        "ensure_dataset(drive_db_zip('yolo_train_db'), '/content/data', 'yolo_train_db')\n"
        "ensure_dataset(drive_db_zip('RF_DETR_Faster_RCNN_train_db'), '/content/data', 'RF_DETR_Faster_RCNN_train_db')",
        "# (Optional) Re-run data-prep from raw mem* if they're on Drive instead of prebuilt DBs\n"
        "# !python -m data_prep.build_dataset --subset all",
        "!python -m data_prep.verify_dataset --subset pole\n"
        "!python -m data_prep.verify_dataset --subset components",
    ],
    "01_train_yolo": _SETUP + [
        "ensure_dataset(drive_db_zip('yolo_train_db'), '/content/data', 'yolo_train_db')",
        "# pole fills the frame -> imgsz 640 (matches train_pole.py default); components need 1280 for thin wires\n"
        "!python -m train_yolo.train_pole --version clahe --epochs 100 --imgsz 640 --batch 16",
        "!python -m train_yolo.train_components --version clahe --epochs 150 --imgsz 1280 --batch 16 --model yolo26m.pt",
    ],
    "02_train_faster_rcnn": _SETUP + [
        "ensure_dataset(drive_db_zip('RF_DETR_Faster_RCNN_train_db'), '/content/data', 'RF_DETR_Faster_RCNN_train_db')",
        "!python -m train_faster_rcnn.train --subset pole --version clahe --epochs 30 --batch 4",
        "!python -m train_faster_rcnn.train --subset components --version clahe --epochs 30 --batch 4",
    ],
    "03_train_rf_detr": _SETUP + [
        "ensure_dataset(drive_db_zip('RF_DETR_Faster_RCNN_train_db'), '/content/data', 'RF_DETR_Faster_RCNN_train_db')",
        "!python -m train_rf_detr.train --subset pole --version clahe --epochs 50 --batch 4",
        "!python -m train_rf_detr.train --subset components --version clahe --epochs 50 --batch 4",
    ],
    "04_inference_pipeline": _SETUP + [
        "# point these at trained weights (on Drive or in runs/)\n"
        "import glob, os\n"
        "POLE=max(glob.glob('runs/pole/yolo*/weights/best.pt'), key=os.path.getmtime)\n"
        "COMP=max(glob.glob('runs/components/yolo*/weights/best.pt'), key=os.path.getmtime)\nprint(POLE, COMP)",
        "import glob\nIMG=sorted(glob.glob('/content/data/yolo_train_db/components/images/test/orig/*.jpg'))[0]\nprint(IMG)",
        "!python -m inference.pipeline --image \"$IMG\" --pole-weights $POLE --comp-weights $COMP --out /content/result.json",
        "import json; print(json.dumps(json.load(open('/content/result.json')), indent=2))",
    ],
}


def _to_notebook(title, cells):
    # Deterministic, content-stable cell ids so regenerating (e.g. after the user
    # sets REPO_URL) yields a clean diff instead of churning random ids each run.
    nb = new_notebook()
    md = new_markdown_cell(f"# {title}\n\nGenerated by `notebooks/build_notebooks.py`. "
                           "Runtime → Change runtime type → GPU, then Run all.")
    md["id"] = f"{title}-md"
    nb.cells.append(md)
    for i, c in enumerate(cells):
        cell = new_code_cell(c)
        cell["id"] = f"{title}-cell-{i}"
        nb.cells.append(cell)
    nb.metadata["accelerator"] = "GPU"
    nb.metadata["colab"] = {"provenance": []}
    return nb


def build_all(out_dir=None):
    out_dir = Path(out_dir or Path(__file__).parent)
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for name, cells in NOTEBOOKS.items():
        nb = _to_notebook(name, cells)
        path = out_dir / f"{name}.ipynb"
        nbformat.write(nb, str(path))
        paths.append(str(path))
    return paths


if __name__ == "__main__":
    for p in build_all():
        print("wrote", p)
